require('vimconf')
require('plugins')
require('evil_lualine')
require('plug-nvim-tree')
require('plug-lspconfig')
require('plug-nvim-cmp')
require('colors')
require('plug-barbar')
require('keymaps')

